### PR TITLE
Support multiple main demuxed by command line argument (test, server, client)

### PR DESCRIPTION
**Pull request by metakirby5**
- Run client with `./aldente`
- Run server with `./aldente server` (unimplemented)
- Run tests with `./aldente test`

### CODE REVIEW

**Review by richard1 — COMMENTED** [review]
Looks alright at first glance. Couple things:

- Was renaming the generated .pb.cc to .pb.cpp necessary to compile? Joshua mentioned something like this

- Might have to do some tweaking on Visual Studio to mirror this functionality. We currently have a bool in the config file called `IsServer` to toggle states, perhaps we can support this way as well? Maybe have the no-command-line-arg case check the config file, and/or add a specific `./aldente client`?

- We can now only spawn either the server or the client. How would local debugging look if I only have one dev machine?

**Comment by metakirby5** [comment]
@richard1 

- Yes, due to Makefile globbing. I'll see if I can use regex as an alternative.
- Try this? https://msdn.microsoft.com/en-us/library/cs8hbt1w(v=vs.90).aspx I'm not a huge fan of using the config file to select server or client, since this is a frequent change you have to make in order to test anything. Arguments seem more reasonable.
- For the stuff we currently have, `./aldente` should work as before. For new stuff, run an instance of the server and an instance of the client. I don't know what you VS kids will do.

**Comment by metakirby5** [comment]
@richard1 Further testing has determined that Makefiles suck. We shall proceed with renaming to `.pb.cpp`.

**Comment by richard1** [comment]
@metakirby5 sure, in that case LGTM after resolving the merge conflict.  We'll need to yank out the config stuff and adjust the `NetworkManager` in a future PR.

**Comment by jytang** [comment]
:ship:
although, can we move test related files to a tests/ subdirectory (catch.h, example_test.cpp)

**Review by jytang — APPROVED** [review]
:ship:
although, can we move test related files to a tests/ subdirectory (catch.h, example_test.cpp)

**Comment by metakirby5** [comment]
@jytang I was actually thinking of doing tests parallel to the `.cpp`/`.h` files so they're easier to locate. What are your thoughts on that?

**Comment by jytang** [comment]
That's fine

**Pull request merged**
